version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrservice
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: 'hrservice'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
